name: WOWOW番組表更新

on:
  schedule:
    - cron: '0 20 * * *'  # 毎日日本時間5時に実行（UTC時間基準）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Restore credentials.json from Base64 using printf
      run: |
        printf "%s" "${{ secrets.CREDENTIALS_JSON_BASE64 }}" | base64 --decode > credentials1.json
      shell: bash

    - name: Debug: Show credentials.json content
      run: |
        cat credentials1.json
      shell: bash

    - name: Run the WOWOW schedule script
      run: |
        python wowow_schedule.py
