name: WOWOW番組表更新

on:
  schedule:
    - cron: '0 20 * * *'  # 毎日日本時間 5:00 に実行（UTC 20時）
  workflow_dispatch:  # 手動実行も可能

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Restore credentials.json
      run: |
        echo "${{ secrets.CREDENTIALS_JSON }}" > credentials1.json

    - name: Run the script
      run: |
        python wowow_schedule.py
